config/routes.rb
Exercicio::Application.routes.draw do

  resources :people do
    member do
      post :sort
    end
    collection do
      post :reorder
    end
  end
  
  resources :animals do
    member do
     post :sort
    end
    collection do
      post :reorder
    end
  end

  

   root :to => 'people#index'

  
end

app/models/animal.rb
class Animal < ActiveRecord::Base
  
  attr_accessible :name
  
  include SortableModel

end

app/models/person.rb
class Person < ActiveRecord::Base
  
  include SortableModel
  
  attr_accessible :name
  
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  # GET /animals
  # GET /animals.json
  def index
    @animals = Animal.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @animals }
    end
  end

  # GET /animals/1
  # GET /animals/1.json
  def show
    @animal = Animal.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @animal }
    end
  end

  # GET /animals/new
  # GET /animals/new.json
  def new
    @animal = Animal.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @animal }
    end
  end

  # GET /animals/1/edit
  def edit
    @animal = Animal.find(params[:id])
  end

  # POST /animals
  # POST /animals.json
  def create
    @animal = Animal.new(params[:animal])

    respond_to do |format|
      if @animal.save
        format.html { redirect_to @animal, notice: 'Animal was successfully created.' }
        format.json { render json: @animal, status: :created, location: @animal }
      else
        format.html { render action: "new" }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /animals/1
  # PUT /animals/1.json
  def update
    @animal = Animal.find(params[:id])

    respond_to do |format|
      if @animal.update_attributes(params[:animal])
        format.html { redirect_to @animal, notice: 'Animal was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /animals/1
  # DELETE /animals/1.json
  def destroy
    @animal = Animal.find(params[:id])
    @animal.destroy

    respond_to do |format|
      format.html { redirect_to animals_url }
      format.json { head :no_content }
    end
  end
  
  def sort
    Animal.update_positions(params[:id],params[:position])
    respond_to do |format|
      format.json { head :no_content }
    end
  end

  def reorder
    Animal.reorder(:name)
    redirect_to animals_path
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController 
     
  # GET /people
  # GET /people.json
  def index
    @people = Person.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @people }
    end
  end

  # GET /people/1
  # GET /people/1.json
  def show
    @person = Person.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/new
  # GET /people/new.json
  def new
    @person = Person.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/1/edit
  def edit
    @person = Person.find(params[:id])
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(params[:person])

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render json: @person, status: :created, location: @person }
      else
        format.html { render action: "new" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /people/1
  # PUT /people/1.json
  def update
    @person = Person.find(params[:id])

    respond_to do |format|
      if @person.update_attributes(params[:person])
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person = Person.find(params[:id])
    @person.destroy

    respond_to do |format|
      format.html { redirect_to people_url }
      format.json { head :no_content }
    end
  end

  def reorder
    Person.reorder(:name)
    redirect_to people_path
  end
  
  def sort
    Person.update_positions(params[:id],params[:position])
    render json: :no_content
  end
  
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper

end

app/views/animals/_animal.html.erb
<%= content_tag "li", data: {sort_path: "#{sort_animal_path(animal)}"}, class: "ui-state-default" do %>
	<span class="ui-icon ui-icon-arrowthick-2-n-s"></span>
	    <%= animal.name %>
	    <%= link_to 'Show', animal, :class => 'person-edit' %> 
	    <%= link_to 'Edit', edit_animal_path(animal), :class => 'person-edit' %> 
	    <%= link_to 'Destroy', animal, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'person-edit' %> 
	</span>
<% end %>

app/views/animals/_form.html.erb
<%= form_for(@animal) do |f| %>
  <% if @animal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@animal.errors.count, "error") %> prohibited this animal from being saved:</h2>

      <ul>
      <% @animal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/animals/edit.html.erb
<h1>Editing animal</h1>

<%= render 'form' %>

<%= link_to 'Show', @animal %> |
<%= link_to 'Back', animals_path %>

app/views/animals/index.html.erb
<h1>Listing animals</h1>

 <p>
    Reorder by <%= link_to 'name', reorder_animals_path, :method => :post %>
 </p>
 
<%= render :partial => 'sortable/list', :locals => {:sortable => @animals} %>
 
<br />

<%= link_to 'New Animal', new_animal_path %>

app/views/animals/new.html.erb
<h1>New animal</h1>

<%= render 'form' %>

<%= link_to 'Back', animals_path %>

app/views/animals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @animal.name %>
</p>

<p>
  <b>Position:</b>
  <%= @animal.position %>
</p>


<%= link_to 'Edit', edit_animal_path(@animal) %> |
<%= link_to 'Back', animals_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Exercicio</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/_person.html.erb
<%= content_tag "li", data: {sort_path: "#{sort_person_path(person)}"}, class: "ui-state-default" do %>
	<span class="ui-icon ui-icon-arrowthick-2-n-s"></span>
	    <%= person.name %>
	    <%= link_to 'Show', person, :class => 'person-edit' %> 
	    <%= link_to 'Edit', edit_person_path(person), :class => 'person-edit' %> 
	    <%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'person-edit' %> 
	</span>
<% end %>

app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<h1>Listing people</h1>
 
 <p>
	Reorder by <%= link_to 'name', reorder_people_path, :method => :post %>
 </p>
 
<%= render :partial => 'sortable/list', :locals => {:sortable => @people} %>
 
<br />

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @person.name %>
</p>

<p>
  <b>Position:</b>
  <%= @person.position %>
</p>


<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>

app/views/sortable/_list.html.erb
<%= content_tag "ul", id: "sortable" do %>

	<%= render sortable %>

<% end %>